package com.watube.yard.util

import android.util.Log
import android.util.LruCache
import com.watube.yard.api.MediaServiceRepository
import com.watube.yard.api.obj.DeArrowContent
import com.watube.yard.api.obj.Streams
import com.watube.yard.constants.PreferenceKeys
import com.watube.yard.helpers.PreferenceHelper

object DeArrowUtil {
    /**
     * Wrapper distinguishing "queried, no DeArrow data" from "never queried": storing a
     * plain null would look exactly like a cache miss, so a video without DeArrow data
     * would hit the API again on every rebind while scrolling.
     */
    private class CachedContent(val value: DeArrowContent?)

    private val cache = LruCache<String, CachedContent>(256)

    private fun extractTitleAndThumbnail(content: DeArrowContent): Pair<String?, String?> {
        val title = content.titles.firstOrNull { it.votes >= 0 || it.locked }?.title
        val thumbnail = content.thumbnails.firstOrNull {
            it.thumbnail != null && !it.original && (it.votes >= 0 || it.locked)
        }?.thumbnail

        return title to thumbnail
    }


    private suspend fun fetchDeArrowContent(videoId: String): DeArrowContent? {
        // prefer cached response, if available (including "no data for this video")
        cache.get(videoId)?.let { return it.value }

        return try {
            MediaServiceRepository.instance.getDeArrowContent(videoId)
                .also { cache.put(videoId, CachedContent(it)) }
        } catch (e: Exception) {
            // failed lookups are not cached so a network error stays retryable
            Log.e(this::class.java.name, "Failed to fetch DeArrow content: ${e.message}")
            null
        }
    }

    /**
     * Apply the new titles and thumbnails generated by DeArrow to the streams item
     */
    suspend fun deArrowStreams(streams: Streams, vidId: String): Streams {
        if (!PreferenceHelper.getBoolean(PreferenceKeys.DEARROW, false)) return streams

        val data = fetchDeArrowContent(vidId) ?: return streams
        val (newTitle, newThumbnail) = extractTitleAndThumbnail(data)

        if (newTitle != null) streams.title = newTitle
        if (newThumbnail != null) streams.thumbnailUrl = newThumbnail

        return streams
    }

    /**
     * If DeArrow is enabled, fetch the alternative title and thumbnail
     */
    suspend fun deArrowVideoId(videoId: String): Pair<String?, String?>? {
        if (!PreferenceHelper.getBoolean(PreferenceKeys.DEARROW, false)) return null

        val data = fetchDeArrowContent(videoId) ?: return null
        return extractTitleAndThumbnail(data)
    }
}